"use client";

import { useState } from "react";
import { Card, CardBody, CardHeader } from "@/components/ui/Card";
import { stocksService } from "@/services/stocks";
import type { StockCalculation, StockCard } from "@/types/api";
import { formatMoney, formatNumber, formatRate } from "@/utils/format";

type Column = StockCard & { investment_calculation: StockCalculation | null; dcf_summary: {status: string; bear_fair_value?: number|null; base_fair_value?: number|null; bull_fair_value?: number|null; base_difference_percent?: number|null; analysis_confidence?: string|null} };
export function StockCompare() {
  const [tickers, setTickers] = useState("HSBK, KCEL"); const [amount, setAmount] = useState("5000000");
  const [columns, setColumns] = useState<Column[]>([]); const [error, setError] = useState<string | null>(null);
  async function compare() { try { setError(null); const ids = tickers.split(/[,\s]+/).filter(Boolean).slice(0, 10); const result = await stocksService.compare(ids, Number(amount)); setColumns(result.columns); } catch (e) { setError(e instanceof Error ? e.message : "Не удалось сравнить"); } }
  const rows: Array<[string, (c: Column) => string]> = [["Цена", c => formatMoney(c.price, c.currency, 2)], ["DCF статус", c => c.dcf_summary.status], ["Bear Fair Value", c => formatMoney(c.dcf_summary.bear_fair_value, c.currency, 0)], ["Base Fair Value", c => formatMoney(c.dcf_summary.base_fair_value, c.currency, 0)], ["Bull Fair Value", c => formatMoney(c.dcf_summary.bull_fair_value, c.currency, 0)], ["Base vs рынок", c => c.dcf_summary.base_difference_percent == null ? "—" : `${c.dcf_summary.base_difference_percent > 0 ? "+" : ""}${formatNumber(c.dcf_summary.base_difference_percent, 1)}%`], ["DCF уверенность", c => c.dcf_summary.analysis_confidence ?? "—"], ["Market Cap", c => formatMoney(c.market_cap, c.currency)], ["P/E", c => formatNumber(c.metrics.pe)], ["P/B", c => formatNumber(c.metrics.pb)], ["EV/EBITDA", c => formatNumber(c.metrics.ev_ebitda)], ["ROE", c => formatRate(c.metrics.roe)], ["Revenue Growth", c => formatRate(c.metrics.revenue_growth)], ["Profit Growth", c => formatRate(c.metrics.earnings_growth)], ["Dividend Yield", c => formatRate(c.metrics.trailing_dividend_yield)], ["Quality", c => formatNumber(c.scores.quality?.value, 0)], ["Valuation", c => formatNumber(c.scores.valuation?.value, 0)], ["Growth", c => formatNumber(c.scores.growth?.value, 0)], ["Liquidity", c => formatNumber(c.scores.liquidity?.value, 0)], ["Risk", c => formatNumber(c.scores.risk?.value, 0)], ["Investment Score", c => formatNumber(c.scores.investment?.value, 0)], ["Количество", c => c.investment_calculation ? `${c.investment_calculation.quantity}` : "—"], ["Остаток", c => formatMoney(c.investment_calculation?.cash_remaining, c.currency)], ["Сценарный результат", c => formatMoney(c.investment_calculation?.scenario_profit, c.currency)]];
  return <Card><CardHeader title="Сравнение акций" subtitle="До 10 акций и одинаковая сумма вложения." /><CardBody className="space-y-4"><div className="grid gap-2 sm:grid-cols-[1fr_12rem_auto]"><input value={tickers} onChange={e => setTickers(e.target.value)} placeholder="HSBK, KCEL" className="h-11 rounded-xl border border-slate-200 bg-transparent px-3 dark:border-slate-700" /><input value={amount} onChange={e => setAmount(e.target.value.replace(/\D/g, ""))} className="h-11 rounded-xl border border-slate-200 bg-transparent px-3 dark:border-slate-700" /><button onClick={compare} className="rounded-xl bg-emerald-600 px-4 text-sm font-semibold text-white">Сравнить</button></div>{error ? <p className="text-sm text-rose-600">{error}</p> : null}{columns.length ? <div className="overflow-x-auto"><table className="w-full min-w-[700px] text-sm"><thead><tr><th className="p-2 text-left text-slate-500">Показатель</th>{columns.map(c => <th key={c.ticker} className="p-2 text-right">{c.ticker}</th>)}</tr></thead><tbody>{rows.map(([label, render]) => <tr key={label} className="border-t border-slate-100 dark:border-slate-800"><td className="p-2 text-slate-500">{label}</td>{columns.map(c => <td key={c.ticker} className="tabular p-2 text-right">{render(c)}</td>)}</tr>)}</tbody></table></div> : null}</CardBody></Card>;
}
