"""initial schema

Revision ID: e0021e518807
Revises: 
Create Date: 2026-08-12 03:22:02.197139+00:00
"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = 'e0021e518807'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('data_sources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('base_url', sa.String(length=512), nullable=True),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('is_authoritative', sa.Boolean(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('last_success_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_failure_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_data_sources'))
    )
    with op.batch_alter_table('data_sources', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_data_sources_code'), ['code'], unique=True)

    op.create_table('fx_rates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('base_currency', sa.String(length=3), nullable=False),
    sa.Column('quote_currency', sa.String(length=3), nullable=False),
    sa.Column('as_of_date', sa.Date(), nullable=False),
    sa.Column('rate', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=True),
    sa.Column('source_identifier', sa.String(length=255), nullable=True),
    sa.Column('source_url', sa.String(length=1024), nullable=True),
    sa.Column('source_timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_fx_rates'))
    )
    with op.batch_alter_table('fx_rates', schema=None) as batch_op:
        batch_op.create_index('ix_fx_pair_date', ['base_currency', 'quote_currency', 'as_of_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_fx_rates_as_of_date'), ['as_of_date'], unique=False)

    op.create_table('inflation_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('country', sa.String(length=2), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=True),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('annual_rate', sa.Float(), nullable=False),
    sa.Column('monthly_rate', sa.Float(), nullable=True),
    sa.Column('horizon_years', sa.Float(), nullable=True),
    sa.Column('note', sa.String(length=512), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=True),
    sa.Column('source_identifier', sa.String(length=255), nullable=True),
    sa.Column('source_url', sa.String(length=1024), nullable=True),
    sa.Column('source_timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_inflation_data'))
    )
    with op.batch_alter_table('inflation_data', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_inflation_data_period_end'), ['period_end'], unique=False)
        batch_op.create_index('ix_inflation_lookup', ['country', 'period_end', 'kind'], unique=False)

    op.create_table('issuers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=512), nullable=False),
    sa.Column('short_name', sa.String(length=255), nullable=True),
    sa.Column('bin', sa.String(length=32), nullable=True),
    sa.Column('country', sa.String(length=2), nullable=False),
    sa.Column('sector', sa.String(length=32), nullable=True),
    sa.Column('industry', sa.String(length=128), nullable=True),
    sa.Column('is_financial_institution', sa.Boolean(), nullable=False),
    sa.Column('is_state_owned', sa.Boolean(), nullable=False),
    sa.Column('website', sa.String(length=512), nullable=True),
    sa.Column('kase_url', sa.String(length=512), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=True),
    sa.Column('source_identifier', sa.String(length=255), nullable=True),
    sa.Column('source_url', sa.String(length=1024), nullable=True),
    sa.Column('source_timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_issuers'))
    )
    with op.batch_alter_table('issuers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_issuers_bin'), ['bin'], unique=False)
        batch_op.create_index(batch_op.f('ix_issuers_code'), ['code'], unique=True)
        batch_op.create_index(batch_op.f('ix_issuers_sector'), ['sector'], unique=False)

    op.create_table('peer_groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('bond_type', sa.String(length=32), nullable=True),
    sa.Column('sector', sa.String(length=32), nullable=True),
    sa.Column('maturity_bucket', sa.String(length=32), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_peer_groups'))
    )
    with op.batch_alter_table('peer_groups', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_peer_groups_code'), ['code'], unique=True)

    op.create_table('raw_kase_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('kind', sa.String(length=64), nullable=False),
    sa.Column('key', sa.String(length=255), nullable=True),
    sa.Column('url', sa.String(length=1024), nullable=True),
    sa.Column('http_status', sa.Integer(), nullable=True),
    sa.Column('content_type', sa.String(length=128), nullable=True),
    sa.Column('payload_json', sa.JSON(), nullable=True),
    sa.Column('payload_text', sa.Text(), nullable=True),
    sa.Column('payload_hash', sa.String(length=64), nullable=True),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('duration_ms', sa.Float(), nullable=True),
    sa.Column('data_mode', sa.String(length=16), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_raw_kase_data'))
    )
    with op.batch_alter_table('raw_kase_data', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_raw_kase_data_fetched_at'), ['fetched_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_raw_kase_data_payload_hash'), ['payload_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_raw_kase_data_source'), ['source'], unique=False)
        batch_op.create_index('ix_raw_kind_key', ['kind', 'key', 'fetched_at'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('display_name', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('yield_curves',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('curve_code', sa.String(length=32), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('as_of_date', sa.Date(), nullable=False),
    sa.Column('tenor_years', sa.Float(), nullable=False),
    sa.Column('yield_rate', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=True),
    sa.Column('source_identifier', sa.String(length=255), nullable=True),
    sa.Column('source_url', sa.String(length=1024), nullable=True),
    sa.Column('source_timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_yield_curves'))
    )
    with op.batch_alter_table('yield_curves', schema=None) as batch_op:
        batch_op.create_index('ix_curve_lookup', ['curve_code', 'as_of_date', 'tenor_years'], unique=False)
        batch_op.create_index(batch_op.f('ix_yield_curves_as_of_date'), ['as_of_date'], unique=False)

    op.create_table('bonds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticker', sa.String(length=64), nullable=False),
    sa.Column('isin', sa.String(length=12), nullable=True),
    sa.Column('issuer_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=512), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('nominal', sa.Float(), nullable=True),
    sa.Column('issue_date', sa.Date(), nullable=True),
    sa.Column('maturity_date', sa.Date(), nullable=True),
    sa.Column('coupon_rate', sa.Float(), nullable=True),
    sa.Column('coupon_type', sa.String(length=16), nullable=True),
    sa.Column('coupon_frequency', sa.Integer(), nullable=True),
    sa.Column('next_coupon_date', sa.Date(), nullable=True),
    sa.Column('day_count', sa.String(length=16), nullable=False),
    sa.Column('issue_size', sa.Float(), nullable=True),
    sa.Column('outstanding_amount', sa.Float(), nullable=True),
    sa.Column('market_segment', sa.String(length=64), nullable=True),
    sa.Column('bond_type', sa.String(length=32), nullable=True),
    sa.Column('secured', sa.Boolean(), nullable=True),
    sa.Column('subordinated', sa.Boolean(), nullable=True),
    sa.Column('callable', sa.Boolean(), nullable=True),
    sa.Column('putable', sa.Boolean(), nullable=True),
    sa.Column('guarantee', sa.Text(), nullable=True),
    sa.Column('kase_url', sa.String(length=512), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('peer_group_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=True),
    sa.Column('source_identifier', sa.String(length=255), nullable=True),
    sa.Column('source_url', sa.String(length=1024), nullable=True),
    sa.Column('source_timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['issuer_id'], ['issuers.id'], name=op.f('fk_bonds_issuer_id_issuers'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['peer_group_id'], ['peer_groups.id'], name=op.f('fk_bonds_peer_group_id_peer_groups'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_bonds'))
    )
    with op.batch_alter_table('bonds', schema=None) as batch_op:
        batch_op.create_index('ix_bonds_active_maturity', ['is_active', 'maturity_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_bonds_bond_type'), ['bond_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_bonds_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_bonds_isin'), ['isin'], unique=True)
        batch_op.create_index(batch_op.f('ix_bonds_issuer_id'), ['issuer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_bonds_maturity_date'), ['maturity_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_bonds_peer_group_id'), ['peer_group_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_bonds_ticker'), ['ticker'], unique=True)

    op.create_table('credit_ratings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('issuer_id', sa.Integer(), nullable=False),
    sa.Column('agency', sa.String(length=64), nullable=False),
    sa.Column('rating', sa.String(length=16), nullable=False),
    sa.Column('scale', sa.String(length=32), nullable=True),
    sa.Column('outlook', sa.String(length=32), nullable=True),
    sa.Column('numeric_grade', sa.Integer(), nullable=True),
    sa.Column('rating_date', sa.Date(), nullable=True),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=True),
    sa.Column('source_identifier', sa.String(length=255), nullable=True),
    sa.Column('source_url', sa.String(length=1024), nullable=True),
    sa.Column('source_timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['issuer_id'], ['issuers.id'], name=op.f('fk_credit_ratings_issuer_id_issuers'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_credit_ratings'))
    )
    with op.batch_alter_table('credit_ratings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_credit_ratings_issuer_id'), ['issuer_id'], unique=False)
        batch_op.create_index('ix_ratings_issuer_agency', ['issuer_id', 'agency'], unique=False)

    op.create_table('financial_statements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('issuer_id', sa.Integer(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('period_type', sa.String(length=8), nullable=False),
    sa.Column('fiscal_year', sa.Integer(), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('is_audited', sa.Boolean(), nullable=True),
    sa.Column('is_consolidated', sa.Boolean(), nullable=True),
    sa.Column('standard', sa.String(length=16), nullable=True),
    sa.Column('revenue', sa.Float(), nullable=True),
    sa.Column('operating_profit', sa.Float(), nullable=True),
    sa.Column('ebitda', sa.Float(), nullable=True),
    sa.Column('net_profit', sa.Float(), nullable=True),
    sa.Column('interest_expense', sa.Float(), nullable=True),
    sa.Column('total_assets', sa.Float(), nullable=True),
    sa.Column('total_equity', sa.Float(), nullable=True),
    sa.Column('total_debt', sa.Float(), nullable=True),
    sa.Column('short_term_debt', sa.Float(), nullable=True),
    sa.Column('long_term_debt', sa.Float(), nullable=True),
    sa.Column('cash_and_equivalents', sa.Float(), nullable=True),
    sa.Column('current_assets', sa.Float(), nullable=True),
    sa.Column('current_liabilities', sa.Float(), nullable=True),
    sa.Column('inventory', sa.Float(), nullable=True),
    sa.Column('operating_cash_flow', sa.Float(), nullable=True),
    sa.Column('investing_cash_flow', sa.Float(), nullable=True),
    sa.Column('financing_cash_flow', sa.Float(), nullable=True),
    sa.Column('capex', sa.Float(), nullable=True),
    sa.Column('free_cash_flow', sa.Float(), nullable=True),
    sa.Column('net_interest_income', sa.Float(), nullable=True),
    sa.Column('net_fee_income', sa.Float(), nullable=True),
    sa.Column('loans_gross', sa.Float(), nullable=True),
    sa.Column('loans_net', sa.Float(), nullable=True),
    sa.Column('npl_amount', sa.Float(), nullable=True),
    sa.Column('loan_loss_provisions', sa.Float(), nullable=True),
    sa.Column('customer_deposits', sa.Float(), nullable=True),
    sa.Column('liquid_assets', sa.Float(), nullable=True),
    sa.Column('tier1_capital', sa.Float(), nullable=True),
    sa.Column('total_capital', sa.Float(), nullable=True),
    sa.Column('risk_weighted_assets', sa.Float(), nullable=True),
    sa.Column('capital_adequacy_ratio', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=True),
    sa.Column('source_identifier', sa.String(length=255), nullable=True),
    sa.Column('source_url', sa.String(length=1024), nullable=True),
    sa.Column('source_timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['issuer_id'], ['issuers.id'], name=op.f('fk_financial_statements_issuer_id_issuers'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_financial_statements'))
    )
    with op.batch_alter_table('financial_statements', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_financial_statements_issuer_id'), ['issuer_id'], unique=False)
        batch_op.create_index('ix_statements_issuer_period', ['issuer_id', 'period_end', 'period_type'], unique=False)

    op.create_table('portfolios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('anonymous_token', sa.String(length=64), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('base_currency', sa.String(length=3), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_portfolios_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_portfolios'))
    )
    with op.batch_alter_table('portfolios', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_portfolios_anonymous_token'), ['anonymous_token'], unique=False)
        batch_op.create_index(batch_op.f('ix_portfolios_user_id'), ['user_id'], unique=False)

    op.create_table('user_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('anonymous_token', sa.String(length=64), nullable=True),
    sa.Column('inflation_enabled', sa.Boolean(), nullable=False),
    sa.Column('inflation_source', sa.String(length=32), nullable=False),
    sa.Column('manual_inflation_rate', sa.Float(), nullable=True),
    sa.Column('show_real_return', sa.Boolean(), nullable=False),
    sa.Column('base_currency', sa.String(length=3), nullable=False),
    sa.Column('ui_mode', sa.String(length=16), nullable=False),
    sa.Column('risk_profile', sa.String(length=16), nullable=False),
    sa.Column('theme', sa.String(length=16), nullable=False),
    sa.Column('remember_calculator_amount', sa.Boolean(), nullable=False),
    sa.Column('calculator_amount', sa.Float(), nullable=True),
    sa.Column('language', sa.String(length=8), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_settings_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_settings'))
    )
    with op.batch_alter_table('user_settings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_settings_anonymous_token'), ['anonymous_token'], unique=True)
        batch_op.create_index(batch_op.f('ix_user_settings_user_id'), ['user_id'], unique=True)

    op.create_table('ai_analyses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bond_id', sa.Integer(), nullable=True),
    sa.Column('issuer_id', sa.Integer(), nullable=True),
    sa.Column('kind', sa.String(length=48), nullable=False),
    sa.Column('language', sa.String(length=8), nullable=False),
    sa.Column('provider', sa.String(length=64), nullable=True),
    sa.Column('model', sa.String(length=128), nullable=True),
    sa.Column('prompt_version', sa.String(length=32), nullable=True),
    sa.Column('inputs', sa.JSON(), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('tokens_prompt', sa.Integer(), nullable=True),
    sa.Column('tokens_completion', sa.Integer(), nullable=True),
    sa.Column('latency_ms', sa.Float(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['bond_id'], ['bonds.id'], name=op.f('fk_ai_analyses_bond_id_bonds'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['issuer_id'], ['issuers.id'], name=op.f('fk_ai_analyses_issuer_id_issuers'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ai_analyses'))
    )
    with op.batch_alter_table('ai_analyses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ai_analyses_bond_id'), ['bond_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ai_analyses_issuer_id'), ['issuer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ai_analyses_kind'), ['kind'], unique=False)
        batch_op.create_index('ix_ai_bond_kind', ['bond_id', 'kind', 'created_at'], unique=False)

    op.create_table('alerts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('bond_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('threshold', sa.Float(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_triggered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['bond_id'], ['bonds.id'], name=op.f('fk_alerts_bond_id_bonds'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_alerts_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_alerts'))
    )
    with op.batch_alter_table('alerts', schema=None) as batch_op:
        batch_op.create_index('ix_alerts_active', ['is_active', 'bond_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_alerts_bond_id'), ['bond_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_alerts_user_id'), ['user_id'], unique=False)

    op.create_table('bond_cashflows',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bond_id', sa.Integer(), nullable=False),
    sa.Column('payment_date', sa.Date(), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=True),
    sa.Column('coupon_amount', sa.Float(), nullable=True),
    sa.Column('principal_amount', sa.Float(), nullable=True),
    sa.Column('total_amount', sa.Float(), nullable=True),
    sa.Column('is_estimated', sa.Boolean(), nullable=False),
    sa.Column('is_final', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=True),
    sa.Column('source_identifier', sa.String(length=255), nullable=True),
    sa.Column('source_url', sa.String(length=1024), nullable=True),
    sa.Column('source_timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['bond_id'], ['bonds.id'], name=op.f('fk_bond_cashflows_bond_id_bonds'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_bond_cashflows'))
    )
    with op.batch_alter_table('bond_cashflows', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_bond_cashflows_bond_id'), ['bond_id'], unique=False)
        batch_op.create_index('ix_cashflows_bond_date', ['bond_id', 'payment_date'], unique=False)

    op.create_table('bond_quotes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bond_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('bid', sa.Float(), nullable=True),
    sa.Column('ask', sa.Float(), nullable=True),
    sa.Column('bid_volume', sa.Float(), nullable=True),
    sa.Column('ask_volume', sa.Float(), nullable=True),
    sa.Column('last', sa.Float(), nullable=True),
    sa.Column('clean_price', sa.Float(), nullable=True),
    sa.Column('dirty_price', sa.Float(), nullable=True),
    sa.Column('accrued_interest', sa.Float(), nullable=True),
    sa.Column('ytm', sa.Float(), nullable=True),
    sa.Column('volume', sa.Float(), nullable=True),
    sa.Column('turnover', sa.Float(), nullable=True),
    sa.Column('number_of_trades', sa.Integer(), nullable=True),
    sa.Column('data_mode', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=True),
    sa.Column('source_identifier', sa.String(length=255), nullable=True),
    sa.Column('source_url', sa.String(length=1024), nullable=True),
    sa.Column('source_timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['bond_id'], ['bonds.id'], name=op.f('fk_bond_quotes_bond_id_bonds'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_bond_quotes'))
    )
    with op.batch_alter_table('bond_quotes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_bond_quotes_bond_id'), ['bond_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_bond_quotes_data_mode'), ['data_mode'], unique=False)
        batch_op.create_index(batch_op.f('ix_bond_quotes_timestamp'), ['timestamp'], unique=False)
        batch_op.create_index('ix_quotes_bond_ts', ['bond_id', 'timestamp'], unique=False)

    op.create_table('bond_scores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bond_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('value', sa.Float(), nullable=True),
    sa.Column('version', sa.String(length=32), nullable=False),
    sa.Column('calculated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('inputs', sa.JSON(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['bond_id'], ['bonds.id'], name=op.f('fk_bond_scores_bond_id_bonds'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_bond_scores_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_bond_scores'))
    )
    with op.batch_alter_table('bond_scores', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_bond_scores_bond_id'), ['bond_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_bond_scores_kind'), ['kind'], unique=False)
        batch_op.create_index(batch_op.f('ix_bond_scores_user_id'), ['user_id'], unique=False)
        batch_op.create_index('ix_scores_bond_kind', ['bond_id', 'kind', 'calculated_at'], unique=False)

    op.create_table('bond_trades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bond_id', sa.Integer(), nullable=False),
    sa.Column('trade_id', sa.String(length=64), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('clean_price', sa.Float(), nullable=True),
    sa.Column('ytm', sa.Float(), nullable=True),
    sa.Column('quantity', sa.Float(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('settlement', sa.String(length=16), nullable=True),
    sa.Column('data_mode', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=True),
    sa.Column('source_identifier', sa.String(length=255), nullable=True),
    sa.Column('source_url', sa.String(length=1024), nullable=True),
    sa.Column('source_timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['bond_id'], ['bonds.id'], name=op.f('fk_bond_trades_bond_id_bonds'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_bond_trades'))
    )
    with op.batch_alter_table('bond_trades', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_bond_trades_bond_id'), ['bond_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_bond_trades_timestamp'), ['timestamp'], unique=False)
        batch_op.create_index(batch_op.f('ix_bond_trades_trade_id'), ['trade_id'], unique=False)
        batch_op.create_index('ix_trades_bond_ts', ['bond_id', 'timestamp'], unique=False)

    op.create_table('issuer_metrics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('issuer_id', sa.Integer(), nullable=False),
    sa.Column('statement_id', sa.Integer(), nullable=True),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('model_kind', sa.String(length=16), nullable=False),
    sa.Column('debt_to_ebitda', sa.Float(), nullable=True),
    sa.Column('net_debt_to_ebitda', sa.Float(), nullable=True),
    sa.Column('debt_to_equity', sa.Float(), nullable=True),
    sa.Column('interest_coverage', sa.Float(), nullable=True),
    sa.Column('current_ratio', sa.Float(), nullable=True),
    sa.Column('quick_ratio', sa.Float(), nullable=True),
    sa.Column('operating_cash_flow', sa.Float(), nullable=True),
    sa.Column('free_cash_flow', sa.Float(), nullable=True),
    sa.Column('roa', sa.Float(), nullable=True),
    sa.Column('roe', sa.Float(), nullable=True),
    sa.Column('ebitda_margin', sa.Float(), nullable=True),
    sa.Column('net_margin', sa.Float(), nullable=True),
    sa.Column('revenue_growth', sa.Float(), nullable=True),
    sa.Column('profit_growth', sa.Float(), nullable=True),
    sa.Column('capital_adequacy_ratio', sa.Float(), nullable=True),
    sa.Column('tier1_ratio', sa.Float(), nullable=True),
    sa.Column('npl_ratio', sa.Float(), nullable=True),
    sa.Column('provision_coverage', sa.Float(), nullable=True),
    sa.Column('loan_to_deposit', sa.Float(), nullable=True),
    sa.Column('liquid_assets_ratio', sa.Float(), nullable=True),
    sa.Column('net_interest_margin', sa.Float(), nullable=True),
    sa.Column('cost_to_income', sa.Float(), nullable=True),
    sa.Column('equity_to_assets', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('formula_version', sa.String(length=32), nullable=True),
    sa.Column('model_version', sa.String(length=32), nullable=True),
    sa.Column('calculated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['issuer_id'], ['issuers.id'], name=op.f('fk_issuer_metrics_issuer_id_issuers'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['statement_id'], ['financial_statements.id'], name=op.f('fk_issuer_metrics_statement_id_financial_statements'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_issuer_metrics'))
    )
    with op.batch_alter_table('issuer_metrics', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_issuer_metrics_issuer_id'), ['issuer_id'], unique=False)
        batch_op.create_index('ix_issuer_metrics_period', ['issuer_id', 'period_end'], unique=False)

    op.create_table('portfolio_positions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('portfolio_id', sa.Integer(), nullable=False),
    sa.Column('bond_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('purchase_clean_price', sa.Float(), nullable=True),
    sa.Column('purchase_date', sa.Date(), nullable=True),
    sa.Column('purchase_accrued_interest', sa.Float(), nullable=True),
    sa.Column('fees', sa.Float(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['bond_id'], ['bonds.id'], name=op.f('fk_portfolio_positions_bond_id_bonds'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolios.id'], name=op.f('fk_portfolio_positions_portfolio_id_portfolios'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_portfolio_positions'))
    )
    with op.batch_alter_table('portfolio_positions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_portfolio_positions_bond_id'), ['bond_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_portfolio_positions_portfolio_id'), ['portfolio_id'], unique=False)

    op.create_table('watchlist',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('anonymous_token', sa.String(length=64), nullable=True),
    sa.Column('bond_id', sa.Integer(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['bond_id'], ['bonds.id'], name=op.f('fk_watchlist_bond_id_bonds'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_watchlist_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_watchlist')),
    sa.UniqueConstraint('anonymous_token', 'bond_id', name='uq_watchlist_anon_bond'),
    sa.UniqueConstraint('user_id', 'bond_id', name='uq_watchlist_user_bond')
    )
    with op.batch_alter_table('watchlist', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_watchlist_anonymous_token'), ['anonymous_token'], unique=False)
        batch_op.create_index(batch_op.f('ix_watchlist_bond_id'), ['bond_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_watchlist_user_id'), ['user_id'], unique=False)

    op.create_table('bond_metrics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bond_id', sa.Integer(), nullable=False),
    sa.Column('quote_id', sa.Integer(), nullable=True),
    sa.Column('as_of', sa.DateTime(timezone=True), nullable=False),
    sa.Column('clean_price', sa.Float(), nullable=True),
    sa.Column('dirty_price', sa.Float(), nullable=True),
    sa.Column('accrued_interest', sa.Float(), nullable=True),
    sa.Column('current_yield', sa.Float(), nullable=True),
    sa.Column('ytm', sa.Float(), nullable=True),
    sa.Column('ytm_source', sa.String(length=32), nullable=True),
    sa.Column('macaulay_duration', sa.Float(), nullable=True),
    sa.Column('modified_duration', sa.Float(), nullable=True),
    sa.Column('convexity', sa.Float(), nullable=True),
    sa.Column('credit_spread', sa.Float(), nullable=True),
    sa.Column('risk_free_rate', sa.Float(), nullable=True),
    sa.Column('bid_ask_spread', sa.Float(), nullable=True),
    sa.Column('bid_ask_spread_pct', sa.Float(), nullable=True),
    sa.Column('pull_to_par', sa.Float(), nullable=True),
    sa.Column('years_to_maturity', sa.Float(), nullable=True),
    sa.Column('real_ytm', sa.Float(), nullable=True),
    sa.Column('inflation_rate_used', sa.Float(), nullable=True),
    sa.Column('inflation_source_used', sa.String(length=32), nullable=True),
    sa.Column('avg_daily_turnover_30d', sa.Float(), nullable=True),
    sa.Column('trading_days_30d', sa.Float(), nullable=True),
    sa.Column('price_volatility_90d', sa.Float(), nullable=True),
    sa.Column('data_mode', sa.String(length=16), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('formula_version', sa.String(length=32), nullable=True),
    sa.Column('model_version', sa.String(length=32), nullable=True),
    sa.Column('calculated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['bond_id'], ['bonds.id'], name=op.f('fk_bond_metrics_bond_id_bonds'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['quote_id'], ['bond_quotes.id'], name=op.f('fk_bond_metrics_quote_id_bond_quotes'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_bond_metrics'))
    )
    with op.batch_alter_table('bond_metrics', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_bond_metrics_as_of'), ['as_of'], unique=False)
        batch_op.create_index(batch_op.f('ix_bond_metrics_bond_id'), ['bond_id'], unique=False)
        batch_op.create_index('ix_metrics_bond_ts', ['bond_id', 'as_of'], unique=False)

    op.create_table('score_components',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('score_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=False),
    sa.Column('value', sa.Float(), nullable=True),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('contribution', sa.Float(), nullable=True),
    sa.Column('raw_value', sa.Float(), nullable=True),
    sa.Column('raw_unit', sa.String(length=32), nullable=True),
    sa.Column('available', sa.Boolean(), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['score_id'], ['bond_scores.id'], name=op.f('fk_score_components_score_id_bond_scores'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_score_components'))
    )
    with op.batch_alter_table('score_components', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_score_components_score_id'), ['score_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('score_components', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_score_components_score_id'))

    op.drop_table('score_components')
    with op.batch_alter_table('bond_metrics', schema=None) as batch_op:
        batch_op.drop_index('ix_metrics_bond_ts')
        batch_op.drop_index(batch_op.f('ix_bond_metrics_bond_id'))
        batch_op.drop_index(batch_op.f('ix_bond_metrics_as_of'))

    op.drop_table('bond_metrics')
    with op.batch_alter_table('watchlist', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_watchlist_user_id'))
        batch_op.drop_index(batch_op.f('ix_watchlist_bond_id'))
        batch_op.drop_index(batch_op.f('ix_watchlist_anonymous_token'))

    op.drop_table('watchlist')
    with op.batch_alter_table('portfolio_positions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_portfolio_positions_portfolio_id'))
        batch_op.drop_index(batch_op.f('ix_portfolio_positions_bond_id'))

    op.drop_table('portfolio_positions')
    with op.batch_alter_table('issuer_metrics', schema=None) as batch_op:
        batch_op.drop_index('ix_issuer_metrics_period')
        batch_op.drop_index(batch_op.f('ix_issuer_metrics_issuer_id'))

    op.drop_table('issuer_metrics')
    with op.batch_alter_table('bond_trades', schema=None) as batch_op:
        batch_op.drop_index('ix_trades_bond_ts')
        batch_op.drop_index(batch_op.f('ix_bond_trades_trade_id'))
        batch_op.drop_index(batch_op.f('ix_bond_trades_timestamp'))
        batch_op.drop_index(batch_op.f('ix_bond_trades_bond_id'))

    op.drop_table('bond_trades')
    with op.batch_alter_table('bond_scores', schema=None) as batch_op:
        batch_op.drop_index('ix_scores_bond_kind')
        batch_op.drop_index(batch_op.f('ix_bond_scores_user_id'))
        batch_op.drop_index(batch_op.f('ix_bond_scores_kind'))
        batch_op.drop_index(batch_op.f('ix_bond_scores_bond_id'))

    op.drop_table('bond_scores')
    with op.batch_alter_table('bond_quotes', schema=None) as batch_op:
        batch_op.drop_index('ix_quotes_bond_ts')
        batch_op.drop_index(batch_op.f('ix_bond_quotes_timestamp'))
        batch_op.drop_index(batch_op.f('ix_bond_quotes_data_mode'))
        batch_op.drop_index(batch_op.f('ix_bond_quotes_bond_id'))

    op.drop_table('bond_quotes')
    with op.batch_alter_table('bond_cashflows', schema=None) as batch_op:
        batch_op.drop_index('ix_cashflows_bond_date')
        batch_op.drop_index(batch_op.f('ix_bond_cashflows_bond_id'))

    op.drop_table('bond_cashflows')
    with op.batch_alter_table('alerts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_alerts_user_id'))
        batch_op.drop_index(batch_op.f('ix_alerts_bond_id'))
        batch_op.drop_index('ix_alerts_active')

    op.drop_table('alerts')
    with op.batch_alter_table('ai_analyses', schema=None) as batch_op:
        batch_op.drop_index('ix_ai_bond_kind')
        batch_op.drop_index(batch_op.f('ix_ai_analyses_kind'))
        batch_op.drop_index(batch_op.f('ix_ai_analyses_issuer_id'))
        batch_op.drop_index(batch_op.f('ix_ai_analyses_bond_id'))

    op.drop_table('ai_analyses')
    with op.batch_alter_table('user_settings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_settings_user_id'))
        batch_op.drop_index(batch_op.f('ix_user_settings_anonymous_token'))

    op.drop_table('user_settings')
    with op.batch_alter_table('portfolios', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_portfolios_user_id'))
        batch_op.drop_index(batch_op.f('ix_portfolios_anonymous_token'))

    op.drop_table('portfolios')
    with op.batch_alter_table('financial_statements', schema=None) as batch_op:
        batch_op.drop_index('ix_statements_issuer_period')
        batch_op.drop_index(batch_op.f('ix_financial_statements_issuer_id'))

    op.drop_table('financial_statements')
    with op.batch_alter_table('credit_ratings', schema=None) as batch_op:
        batch_op.drop_index('ix_ratings_issuer_agency')
        batch_op.drop_index(batch_op.f('ix_credit_ratings_issuer_id'))

    op.drop_table('credit_ratings')
    with op.batch_alter_table('bonds', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bonds_ticker'))
        batch_op.drop_index(batch_op.f('ix_bonds_peer_group_id'))
        batch_op.drop_index(batch_op.f('ix_bonds_maturity_date'))
        batch_op.drop_index(batch_op.f('ix_bonds_issuer_id'))
        batch_op.drop_index(batch_op.f('ix_bonds_isin'))
        batch_op.drop_index(batch_op.f('ix_bonds_is_active'))
        batch_op.drop_index(batch_op.f('ix_bonds_bond_type'))
        batch_op.drop_index('ix_bonds_active_maturity')

    op.drop_table('bonds')
    with op.batch_alter_table('yield_curves', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_yield_curves_as_of_date'))
        batch_op.drop_index('ix_curve_lookup')

    op.drop_table('yield_curves')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('raw_kase_data', schema=None) as batch_op:
        batch_op.drop_index('ix_raw_kind_key')
        batch_op.drop_index(batch_op.f('ix_raw_kase_data_source'))
        batch_op.drop_index(batch_op.f('ix_raw_kase_data_payload_hash'))
        batch_op.drop_index(batch_op.f('ix_raw_kase_data_fetched_at'))

    op.drop_table('raw_kase_data')
    with op.batch_alter_table('peer_groups', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_peer_groups_code'))

    op.drop_table('peer_groups')
    with op.batch_alter_table('issuers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_issuers_sector'))
        batch_op.drop_index(batch_op.f('ix_issuers_code'))
        batch_op.drop_index(batch_op.f('ix_issuers_bin'))

    op.drop_table('issuers')
    with op.batch_alter_table('inflation_data', schema=None) as batch_op:
        batch_op.drop_index('ix_inflation_lookup')
        batch_op.drop_index(batch_op.f('ix_inflation_data_period_end'))

    op.drop_table('inflation_data')
    with op.batch_alter_table('fx_rates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_fx_rates_as_of_date'))
        batch_op.drop_index('ix_fx_pair_date')

    op.drop_table('fx_rates')
    with op.batch_alter_table('data_sources', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_data_sources_code'))

    op.drop_table('data_sources')
    # ### end Alembic commands ###
