"""News intelligence and event impact engine.

Revision ID: d8e4f53a0177
Revises: c7d3e42f9066
"""
from collections.abc import Sequence
from alembic import op
import sqlalchemy as sa

revision: str = "d8e4f53a0177"
down_revision: str | None = "c7d3e42f9066"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

def upgrade() -> None:
    op.create_table("news_articles", sa.Column("id",sa.Integer(),primary_key=True),sa.Column("source",sa.String(64),nullable=False),sa.Column("source_url",sa.String(2048),nullable=False),sa.Column("canonical_url",sa.String(2048),nullable=False),sa.Column("title",sa.String(1024),nullable=False),sa.Column("published_at",sa.DateTime(timezone=True),nullable=False),sa.Column("fetched_at",sa.DateTime(timezone=True),nullable=False),sa.Column("language",sa.String(8)),sa.Column("section",sa.String(128)),sa.Column("content_hash",sa.String(64),nullable=False),sa.Column("fingerprint",sa.String(64),nullable=False),sa.Column("short_text",sa.Text()),sa.Column("summary",sa.Text()),sa.Column("source_confidence",sa.Float(),nullable=False),sa.Column("is_processed",sa.Boolean(),nullable=False),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False),sa.Column("updated_at",sa.DateTime(timezone=True),nullable=False),sa.UniqueConstraint("source","canonical_url",name="uq_news_article_source_url"),sa.UniqueConstraint("fingerprint",name="uq_news_article_fingerprint"))
    op.create_index("ix_news_articles_published","news_articles",["published_at"]); op.create_index("ix_news_articles_content_hash","news_articles",["content_hash"]); op.create_index("ix_news_articles_is_processed","news_articles",["is_processed"]); op.create_index("ix_news_articles_source","news_articles",["source"])
    op.create_table("company_aliases",sa.Column("id",sa.Integer(),primary_key=True),sa.Column("issuer_id",sa.Integer(),sa.ForeignKey("issuers.id",ondelete="CASCADE"),nullable=False),sa.Column("alias",sa.String(512),nullable=False),sa.Column("normalized_alias",sa.String(512),nullable=False),sa.Column("alias_type",sa.String(32),nullable=False),sa.Column("confidence",sa.Float(),nullable=False),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False),sa.Column("updated_at",sa.DateTime(timezone=True),nullable=False),sa.UniqueConstraint("normalized_alias","issuer_id",name="uq_company_alias_issuer")); op.create_index("ix_company_aliases_issuer_id","company_aliases",["issuer_id"]);op.create_index("ix_company_aliases_normalized_alias","company_aliases",["normalized_alias"])
    op.create_table("event_clusters",sa.Column("id",sa.Integer(),primary_key=True),sa.Column("canonical_news_id",sa.Integer(),sa.ForeignKey("news_articles.id",ondelete="SET NULL")),sa.Column("cluster_key",sa.String(64),nullable=False,unique=True),sa.Column("title",sa.String(1024),nullable=False),sa.Column("article_count",sa.Integer(),nullable=False),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False),sa.Column("updated_at",sa.DateTime(timezone=True),nullable=False));op.create_index("ix_event_clusters_canonical_news_id","event_clusters",["canonical_news_id"]);op.create_index("ix_event_clusters_cluster_key","event_clusters",["cluster_key"])
    op.create_table("news_cluster_members",sa.Column("id",sa.Integer(),primary_key=True),sa.Column("cluster_id",sa.Integer(),sa.ForeignKey("event_clusters.id",ondelete="CASCADE"),nullable=False),sa.Column("news_id",sa.Integer(),sa.ForeignKey("news_articles.id",ondelete="CASCADE"),nullable=False),sa.Column("similarity",sa.Float(),nullable=False),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False),sa.Column("updated_at",sa.DateTime(timezone=True),nullable=False),sa.UniqueConstraint("news_id",name="uq_news_cluster_member"));op.create_index("ix_news_cluster_members_cluster_id","news_cluster_members",["cluster_id"]);op.create_index("ix_news_cluster_members_news_id","news_cluster_members",["news_id"])
    op.create_table("market_events",sa.Column("id",sa.Integer(),primary_key=True),sa.Column("news_id",sa.Integer(),sa.ForeignKey("news_articles.id",ondelete="CASCADE"),nullable=False),sa.Column("cluster_id",sa.Integer(),sa.ForeignKey("event_clusters.id",ondelete="SET NULL")),sa.Column("event_type",sa.String(32),nullable=False),sa.Column("event_timestamp",sa.DateTime(timezone=True),nullable=False),sa.Column("issuer_id",sa.Integer(),sa.ForeignKey("issuers.id",ondelete="SET NULL")),sa.Column("instrument_id",sa.Integer(),sa.ForeignKey("instruments.id",ondelete="SET NULL")),sa.Column("sector",sa.String(128)),sa.Column("country",sa.String(2)),sa.Column("importance",sa.Float(),nullable=False),sa.Column("sentiment",sa.Float()),sa.Column("surprise",sa.Float()),sa.Column("market_regime",sa.String(32)),sa.Column("source_confidence",sa.Float(),nullable=False),sa.Column("analysis_confidence",sa.Float(),nullable=False),sa.Column("relevance",sa.Float(),nullable=False),sa.Column("entities",sa.JSON()),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False),sa.Column("updated_at",sa.DateTime(timezone=True),nullable=False))
    for name,cols in (("ix_market_events_news_id",["news_id"]),("ix_market_events_cluster_id",["cluster_id"]),("ix_market_events_event_type",["event_type"]),("ix_market_events_event_timestamp",["event_timestamp"]),("ix_market_events_issuer_id",["issuer_id"]),("ix_market_events_instrument_id",["instrument_id"]),("ix_market_events_sector",["sector"]),("ix_market_events_country",["country"]),("ix_market_events_market_regime",["market_regime"]),("ix_market_events_instrument_ts",["instrument_id","event_timestamp"])): op.create_index(name,"market_events",cols)
    op.create_table("event_market_reactions",sa.Column("id",sa.Integer(),primary_key=True),sa.Column("event_id",sa.Integer(),sa.ForeignKey("market_events.id",ondelete="CASCADE"),nullable=False),sa.Column("instrument_id",sa.Integer(),sa.ForeignKey("instruments.id",ondelete="CASCADE"),nullable=False),sa.Column("benchmark_id",sa.Integer(),sa.ForeignKey("instruments.id",ondelete="SET NULL")),*[sa.Column(name,sa.Float()) for name in ("price_before","return_5m","return_30m","return_1h","return_same_day","return_1d","return_5d","return_20d","volume_ratio","volatility_change","market_return","sector_return","abnormal_return_1d","abnormal_return_5d")],sa.Column("formula_version",sa.String(32),nullable=False),sa.Column("calculated_at",sa.DateTime(timezone=True),nullable=False),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False),sa.Column("updated_at",sa.DateTime(timezone=True),nullable=False),sa.UniqueConstraint("event_id","instrument_id",name="uq_event_instrument_reaction"));op.create_index("ix_event_market_reactions_event_id","event_market_reactions",["event_id"]);op.create_index("ix_event_market_reactions_instrument_id","event_market_reactions",["instrument_id"]);op.create_index("ix_event_market_reactions_benchmark_id","event_market_reactions",["benchmark_id"])
    op.create_table("news_impact_scores",sa.Column("id",sa.Integer(),primary_key=True),sa.Column("event_id",sa.Integer(),sa.ForeignKey("market_events.id",ondelete="CASCADE"),nullable=False),sa.Column("value",sa.Float(),nullable=False),sa.Column("formula_version",sa.String(32),nullable=False),sa.Column("components",sa.JSON(),nullable=False),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False),sa.Column("updated_at",sa.DateTime(timezone=True),nullable=False),sa.UniqueConstraint("event_id","formula_version",name="uq_event_impact_version"));op.create_index("ix_news_impact_scores_event_id","news_impact_scores",["event_id"])
    op.create_table("notification_candidates",sa.Column("id",sa.Integer(),primary_key=True),sa.Column("event_id",sa.Integer(),sa.ForeignKey("market_events.id",ondelete="CASCADE"),nullable=False),sa.Column("audience_type",sa.String(32),nullable=False),sa.Column("audience_key",sa.String(128),nullable=False),sa.Column("importance",sa.Float(),nullable=False),sa.Column("status",sa.String(16),nullable=False),sa.Column("reason",sa.Text(),nullable=False),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False),sa.Column("updated_at",sa.DateTime(timezone=True),nullable=False),sa.UniqueConstraint("event_id","audience_type","audience_key",name="uq_event_notification_audience"));op.create_index("ix_notification_candidates_event_id","notification_candidates",["event_id"]);op.create_index("ix_notification_candidates_status","notification_candidates",["status"])

def downgrade() -> None:
    for table in ("notification_candidates","news_impact_scores","event_market_reactions","market_events","news_cluster_members","event_clusters","company_aliases","news_articles"): op.drop_table(table)
