"""Make ``app.*`` importable from the ai/ tree without installing the backend.

The AI system deliberately reuses the product's real calculation and scoring
engines rather than reimplementing them: if the dataset were generated by a
second, parallel implementation of YTM, the model would be trained on numbers
the product never produces (§59).
"""

from __future__ import annotations

import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
BACKEND = REPO_ROOT / "backend"

for path in (REPO_ROOT, BACKEND):
    text = str(path)
    if text not in sys.path:
        sys.path.insert(0, text)

__all__ = ["REPO_ROOT", "BACKEND"]
